project_name: a
exp_name: T3000
use_wandb: False
wandb_entity: ammar
train_root: ~
val_root: ./Split_Original/test/
data_size: 384
num_workers: 2
batch_size: 16
model_name: swin-t
pretrained: /cluster/home/ammaa/Downloads/Ammars/Models/PIM/FGVC-Multi/records/WristAb_Lion_FPN-1024/T3000/backup/best.pt
optimizer: Lion
max_lr: 0.000005
wdecay: 0.0005
max_epochs: 100
warmup_batchs: 800
use_amp: True
use_fpn: True
fpn_size: 1024
use_selection: True
num_classes: 4
num_selects: 
  layer1: 2048
  layer2: 512
  layer3: 128
  layer4: 32
use_combiner: True
lambda_b: 0.5
lambda_s: 0.0
lambda_n: 5.0
lambda_c: 1.0
update_freq: 2
log_freq: 100
eval_freq: 10